config/routes.rb
Rails.application.routes.draw do
  resources :records
  resources :reviews
  resources :contacts
  resources :services
  resources :users
  resources :user_sessions
  resources :welcomes

  # resources :sessions, only: [:new, :create, :destroy]
  root 'welcomes#index'

  # match '/new',    to: 'user_sessions#new',    via: 'get'
  #
  # match '/create',    to: 'user_sessions#create',    via: 'get'
  #
  # match '/destroy',    to: 'user_sessions#destroy',    via: 'get'

  match '/new',    to: 'welcomes#new',    via: 'get'
  match '/create',    to: 'welcomes#create',    via: 'get'
  match '/destroy',    to: 'welcomes#destroy',    via: 'get'

  match '/admin', to: 'users#admin', via: 'get'
  match '/master', to: 'users#master', via: 'get'
  match '/customer', to: 'users#customer', via: 'get'


  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  #
  # get 'user_sessions/new'
  #
  # get 'user_sessions/create'
  #
  # get 'user_sessions/destroy'





end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :records, dependent: :destroy
  has_many :reviews, dependent: :destroy

  include PgSearch
  pg_search_scope :search_everywhere, against: [:login, :name]

  has_many :reviews
  authenticates_with_sorcery!
  has_attached_file :avatar, styles: {medium: '300x300', thumb: '100x100', crug: 'border-radius:50%'}
  validates_attachment :avatar, content_type: {content_type: ['image/jpg','image/jpeg','image/png','image/gif']}
  validates :fio, presence: true
  validates :login, presence: true, uniqueness: true
  validates :roles, presence: true
  validates_presence_of :password, if: :password_required?
  validates_confirmation_of :password, if: :password_required?
  validates_length_of :password, within: 5..255, allow_blank: true

  scope :ordering,->{order(:login)}


  def admin?
    self.roles && self.roles.include?("admin")
  end
  def master?
    self.roles && self.roles.include?("master")
  end
  def customer?
    self.roles && self.roles.include?("customer")
  end

  private
  def password_required?
    self.new_record? || password.present? || password_confirmation.present?
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :admin_user, only: :destroy
  # before_action :only_for_admin

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    @users = User.ordering.page(params[:page])
    # @user_teachers = User.where("roles='teacher'").all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    # @otziv = Review.where("user_id=current_user.id").all
    # @user_teacher = Use r.where("roles='teacher'").find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  # def create
  #   @user = User.new(user_params)
  #   respond_to do |format|
  #     if @user.save
  #       format.html { redirect_to users_path, notice: 'Пользователь успешно создан.' }
  #       format.json { render :show, status: :created, location: @user }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  # def create
  #   @user = User.new(user_params)
  #   if @user.save
  #     flash[:success] = "Welcome to the Sample App!"
  #     redirect_to @user
  #   else
  #     render 'new'
  #   end
  # end
  def create
    @user = User.new(user_params)
    if @user.save
      if current_user.try('admin?') || current_user.try('master?')
      flash[:success] = 'Пользователь создан.'
      redirect_to users_path
      else
        session[:user_id]=@user.id
        flash[:success] = "Регистрация выполнена."
        redirect_to root_path
      end
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        flash[:success] = 'Пользователь успешно изменен.'
        format.html { redirect_to users_path}
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json

  # def destroy
  #   @user.destroy
  #   respond_to do |format|
  #     format.html { redirect_to users_url, notice: 'Пользователь успешно удален.' }
  #     format.json { head :no_content }
  #   end
  # end
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Пользователь успешно удален."
    redirect_to users_url
  end

  def admin
    if current_user.try('admin?')
      @admin = User.where("roles=?", 'admin').all
    # else
    #   flash[:success] = "Вы не админ!"
    end
  end
  def master
      @master = User.where("roles=?", 'master').page(params[:page]).per(10)
    # else
    #   flash[:success] = "Вы не админ!"
  end
  def customer
    if current_user.try('admin?')
      @customer = User.where("roles=?", 'customer').all
    # else
      # flash[:success] = "Вы не админ!"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      if !params[:user][:roles].nil?
        if params[:user][:roles] != 'admin' && params[:user][:roles] != 'customer' &&params[:user][:roles] != 'master'
          params[:user][:roles] = ''
        end
      else
        params[:user][:roles] = 'customer'
      end
      params.require(:user).permit(:fio, :login, :password, :password_confirmation, :roles, :avatar)
    end
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/views/users/_form.html.haml
= form_for @user, :html => {:multipart => true} do |f|
  =error_messages_for @user

  .form-group
    = f.label :fio
    = f.text_field :fio, class: "form-control"
  .form-group
    = f.label :login
    = f.text_field :login, class: "form-control"
  .form-group
    = f.label :password
    = f.password_field :password, class: "form-control"
  .form-group
    = f.label :password_confirmation
    = f.password_field :password_confirmation, class: "form-control"
  .form-group
    = f.label :avatar
    = f.file_field :avatar


  - chckedValue = @user.roles ? @user.roles.split : []
  - if current_user.try('admin?')
    .form-group
      = f.label :roles
      = f.select :roles, [["Администратор", "admin"], ["Мастер", "master"], ["Клиент", "customer"]],{:prompt => "Выберите роли", :selected => chckedValue}

  - if current_user.try('master?')
    .form-group
      = f.label :roles
      = f.select :roles, [["Мастер", "master"], ["Клиент", "customer"]],{:prompt => "Выберите роли", :selected => chckedValue}
  .actions
    = f.submit 'Сохранить', class: "btn btn-default"

app/views/users/admin.html.haml
- if current_user.try('admin?')
  %li= link_to "Все пользователи", users_path
  %li= link_to "Список мастеров", master_path
  %li= link_to "Список клиентов", customer_path
  -if @admin.count > 0

    %h1 Список пользователей

    %table.table
      %tr
        %th= User.human_attribute_name(:fio)
        %th= User.human_attribute_name(:login)
        %th= User.human_attribute_name(:roles)
        %th
        %th
        %th
        %th

      - @admin.each do |admin|
        %tr
          %td= admin.fio
          %td= admin.login
          %td= admin.roles
          %td= link_to 'Просмотр', admin
          %td= link_to 'Изменить', edit_user_path(admin)
          %td= link_to 'Удалить', admin, :method => :delete, :data => { :confirm => 'Вы уверены?' }

    %br

    = link_to 'Создать нового пользователя', new_user_path
  -else
    %h3 Нет ниодного администратора
- else
  %h1 Доступ запрещен

app/views/users/customer.html.haml
- if current_user.try('admin?')
  %li= link_to "Все пользователи", users_path
  %li= link_to "Список администаторов", admin_path
  %li= link_to "Список мастеров", master_path
  -if @customer.count > 0

    %h1 Список пользователей

    %table.table
      %tr
        %th= User.human_attribute_name(:fio)
        %th= User.human_attribute_name(:login)
        %th= User.human_attribute_name(:roles)
        %th
        %th
        %th
        %th

      - @customer.each do |customer|
        %tr
          %td= customer.fio
          %td= customer.login
          %td= customer.roles
          %td= link_to 'Просмотр', customer
          %td= link_to 'Изменить', edit_user_path(customer)
          %td= link_to 'Удалить', customer, :method => :delete, :data => { :confirm => 'Вы уверены?' }

    %br

    = link_to 'Создать нового пользователя', new_user_path
  -else
    %h3 Нет ниодного клиента
- else
  %h1 Доступ запрещен

app/views/users/edit.html.haml
%h1 Редактирование пользователя

= render 'form'

= link_to 'Показать пользователя', @user
\|
= link_to 'Список пользователей', users_path

app/views/users/index.html.haml
-#- if current_user.try('admin?')
-#  %li= link_to "Список администаторов", admin_path
-#  %li= link_to "Список мастеров", master_path
-#  %li= link_to "Список клиентов", customer_path
-#
-#  %h1 Список пользователей
-#
-#  %table.table
-#    %tr
-#      %th= User.human_attribute_name(:fio)
-#      %th= User.human_attribute_name(:login)
-#      %th= User.human_attribute_name(:roles)
-#      %th
-#      %th
-#      %th
-#      %th
-#
-#    - @users.each do |user|
-#      %tr
-#        %td= user.fio
-#        %td= user.login
-#        %td= user.roles
-#        %td= link_to 'Просмотр', user
-#        %td= link_to 'Изменить', edit_user_path(user)
-#        %td= link_to 'Удалить', user, :method => :delete, :data => { :confirm => 'Вы уверены?' }
-#
-#  %br
-#
-#  = link_to 'Создать нового пользователя', new_user_path
-#- else
-#  %h1 Доступ запрещен

- if current_user.try('admin?')
  .page-header
    %h1
      Пользователи
      - if current_user.try('admin?')
        =link_to new_user_path,class: 'btn btn-primary' do
          =fa_icon 'plus'
  .list-group
    -@users.each do |user|
      .list-group-item
        .pull-right
          =link_to user, class: 'btn btn-primary btn-sm' do
            =fa_icon 'eye'
          =link_to edit_user_path(user), class: 'btn btn-primary btn-sm' do
            =fa_icon 'edit'
          =link_to user, method: :delete, data: {confirm: t('helpers.sure')}, class: 'btn btn-danger btn-sm' do
            =fa_icon 'trash-o'
        %h4=link_to user.login,user
        .text-muted=user.roles
        .clearfix
  =paginate @users

app/views/users/master.html.haml
-#- if current_user.try('admin?')
-#  %li= link_to "Все пользователи", users_path
-#  %li= link_to "Список клиентов", customer_path
-#  %li= link_to "Список администаторов", admin_path
-#-if @master.count > 0
-#
-#  %h1 Список пользователей
-#
-#  %table.table
-#    %tr
-#      %th= User.human_attribute_name(:fio)
-#      %th= User.human_attribute_name(:login)
-#      %th= User.human_attribute_name(:roles)
-#      %th
-#      %th
-#      %th
-#      %th
-#
-#    - @master.each do |master|
-#      %tr
-#        %td= master.fio
-#        %td= master.login
-#        %td= master.roles
-#        %td= link_to 'Просмотр', master
-#        %td= link_to 'Изменить', edit_user_path(master)
-#        %td= link_to 'Удалить', master, :method => :delete, :data => { :confirm => 'Вы уверены?' }
-#
-#  %br
-#
-#-else
-#  %h3 Нет ниодного мастера
-#
-#  = link_to 'Добавить мастера', new_user_path
-#-#- else
-#-#  %h1 Доступ запрещен




%h1 Список мастеров
= paginate @master



- @master.in_groups_of(3, false) do |master|
  .row
    -for p in master
      %div{id: dom_id(p)}
        .col-md-4
          .thumbnail
            .pppp
              .row
                .col-md-6
                  -if p.avatar?
                    .div{:style=>"border:1px;border-style: solid;border-radius:15px;margin:1px;width:302px;height:242px;"}
                      %a{:href=>p.avatar.url, :rel=>"gallery"}
                        =image_tag p.avatar.url(:medium), alt: p.login, :class=>"margin-photo"
                -#=link_to p.image.url do
                -#  =image_tag p.image.url(:thumb), alt: p.name, :class => 'img-rounded'
                .col-md-6
                  =p.login
                  -#%br
                  -#= link_to "#{p.category.try(:name)}", p.category
                  -#%br
                  -#= link_to "#{p.brand.try(:name)}", p.brand
              .row
                .col-md-12
                  %b Описание:
                  = p.salt




                  %br
                  = link_to 'Показать', p, class: 'btn btn-primary btn-xs'
                  %br
                    -if session[:user_id]
                      .row
                        -#%br
                        -#.col-md-offset-5
                        -#  = link_to "Добавить к сравнению", add_comparison_path(p), class: 'btn-warning btn-xs'
                        %br
                        .col-md-8
                          = link_to 'Редактировать',  edit_user_path(p),  class: 'btn btn-warning btn-xs'
                        .col-md
                          = link_to 'Удалить', p, :method => :delete, :data => { :confirm => 'Вы действительно хотите удалить этот продукт?', remote: true }, class: 'btn btn-warning btn-xs'


=paginate @master
%br
-if session[:user_id]
  = link_to 'Новый', new_user_path, :class => "btn btn-primary"

app/views/users/new.html.haml
%h1 Новый пользователь

= render 'form'

app/views/users/show.html.haml
-#- if current_user.try('admin?')
.row
  .col-sm-3
    -if @user.avatar?
      =image_tag @user.avatar.url, alt: @user.login
    %p
      %b=User.human_attribute_name(:fio)
      = @user.fio

    %p
      %b=User.human_attribute_name(:login)
      = @user.login

    %p
      %b=User.human_attribute_name(:roles)
      = @user.roles

= link_to 'Редактировать', edit_user_path(@user), class: "btn btn-default"
- if current_user.try('admin?')
  \|
  = link_to 'Список пользователей', users_path, class: "btn btn-default"