config/routes.rb
Rails.application.routes.draw do
  resources :records
  resources :reviews
  resources :contacts
  resources :services
  resources :users
  resources :user_sessions
  resources :welcomes

  # resources :sessions, only: [:new, :create, :destroy]
  root 'welcomes#index'

  # match '/new',    to: 'user_sessions#new',    via: 'get'
  #
  # match '/create',    to: 'user_sessions#create',    via: 'get'
  #
  # match '/destroy',    to: 'user_sessions#destroy',    via: 'get'

  match '/new',    to: 'welcomes#new',    via: 'get'
  match '/create',    to: 'welcomes#create',    via: 'get'
  match '/destroy',    to: 'welcomes#destroy',    via: 'get'

  match '/admin', to: 'users#admin', via: 'get'
  match '/master', to: 'users#master', via: 'get'
  match '/customer', to: 'users#customer', via: 'get'


  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  #
  # get 'user_sessions/new'
  #
  # get 'user_sessions/create'
  #
  # get 'user_sessions/destroy'





end

app/models/record.rb
class Record < ActiveRecord::Base
  has_and_belongs_to_many :services
  belongs_to :user
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: [:show, :edit, :update, :destroy]

  # GET /records
  # GET /records.json
  def index
    @records = Record.all
  end

  # GET /records/1
  # GET /records/1.json
  def show
  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(record_params)

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: 'Record was successfully created.' }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url, notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.require(:record).permit(:fio, :number, :data, :time)
    end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_form.html.haml
= form_for @record do |f|
  - if @record.errors.any?
    #error_explanation
      %h2= "#{pluralize(@record.errors.count, "error")} prohibited this record from being saved:"
      %ul
        - @record.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :fio
    = f.text_field :fio
  .field
    = f.label :number
    = f.text_field :number
  .field
    = f.label :data
    = f.date_select :data
  .field
    = f.label :time
    = f.time_select :time
  .actions
    = f.submit 'Save'

app/views/records/edit.html.haml
%h1 Editing record

= render 'form'

= link_to 'Show', @record
\|
= link_to 'Back', records_path

app/views/records/index.html.haml
%h1 Listing records

%table
  %thead
    %tr
      %th Fio
      %th Number
      %th Data
      %th Time
      %th
      %th
      %th

  %tbody
    - @records.each do |record|
      %tr
        %td= record.fio
        %td= record.number
        %td= record.data
        %td= record.time
        %td= link_to 'Show', record
        %td= link_to 'Edit', edit_record_path(record)
        %td= link_to 'Destroy', record, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Record', new_record_path

app/views/records/new.html.haml
%h1 New record

= render 'form'

= link_to 'Back', records_path

app/views/records/show.html.haml
%p#notice= notice

%p
  %b Fio:
  = @record.fio
%p
  %b Number:
  = @record.number
%p
  %b Data:
  = @record.data
%p
  %b Time:
  = @record.time

= link_to 'Edit', edit_record_path(@record)
\|
= link_to 'Back', records_path