config/routes.rb
Rails.application.routes.draw do
  resources :records
  resources :reviews
  resources :contacts
  resources :services
  resources :users
  resources :user_sessions
  resources :welcomes

  # resources :sessions, only: [:new, :create, :destroy]
  root 'welcomes#index'

  # match '/new',    to: 'user_sessions#new',    via: 'get'
  #
  # match '/create',    to: 'user_sessions#create',    via: 'get'
  #
  # match '/destroy',    to: 'user_sessions#destroy',    via: 'get'

  match '/new',    to: 'welcomes#new',    via: 'get'
  match '/create',    to: 'welcomes#create',    via: 'get'
  match '/destroy',    to: 'welcomes#destroy',    via: 'get'

  match '/admin', to: 'users#admin', via: 'get'
  match '/master', to: 'users#master', via: 'get'
  match '/customer', to: 'users#customer', via: 'get'


  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  #
  # get 'user_sessions/new'
  #
  # get 'user_sessions/create'
  #
  # get 'user_sessions/destroy'





end

app/models/welcome.rb
class Welcome < ActiveRecord::Base
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  before_action :set_welcome, only: [:edit, :update, :destroy]
  before_action :only_for_admin, only: [:edit, :update, :destroy, :create]
  # GET /welcomes
  # GET /welcomes.json
  def index
    @welcomes = Welcome.all
  end


  # GET /welcomes/new
  def new
    if Welcome.count==0
      @welcome = Welcome.new
    else
      redirect_to root_path
    end
  end

  # GET /welcomes/1/edit
  def edit
  end

  # POST /welcomes
  # POST /welcomes.json
  # def create
  #   @welcome = Welcome.new(welcome_params)
  #
  #   respond_to do |format|
  #     if @welcome.save
  #       format.html { redirect_to @welcome, notice: 'Welcome was successfully created.' }
  #       format.json { render :show, status: :created, location: @welcome }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @welcome.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  def create
    if Welcome.count==0
      @welcome = Welcome.new(welcome_params)
      if @welcome.save
        flash[:success] = 'Главная страница созданна.'
        redirect_to root_path
      else
        render :new
      end
    else
      redirect_to root_path
    end
  end

  # # PATCH/PUT /welcomes/1
  # # PATCH/PUT /welcomes/1.json
  # def update
  #   respond_to do |format|
  #     if @welcome.update(welcome_params)
  #       format.html { redirect_to @welcome, notice: 'Welcome was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @welcome }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @welcome.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  def update
    if @welcome.update(welcome_params)
      flash[:success] = 'Главная страница изменена'
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
    @welcome = Welcome.find(params[:id])
  end
  # DELETE /welcomes/1
  # DELETE /welcomes/1.json
  def destroy
    @welcome.destroy
    respond_to do |format|
      flash[:success] = 'Данные с главной страницы удалены.'
      format.html { redirect_to welcomes_url}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_welcome
      @welcome = Welcome.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def welcome_params
      params.require(:welcome).permit(:description)
    end
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/welcomes/_form.html.haml
= form_for @welcome do |f|
  - if @welcome.errors.any?
    #error_explanation
      %h2= "#{pluralize(@welcome.errors.count, "error")} prohibited this welcome from being saved:"
      %ul
        - @welcome.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit nil, class: 'btn btn-primary'

app/views/welcomes/edit.html.haml
%h1 Редактирование главной страницы

= render 'form'

app/views/welcomes/index.html.haml
%h1.text-center Добро пожаловать11
-#
-#%table
-#  %thead
-#    %tr
-#      %th Description
-#      %th
-#      %th
-#      %th
-#
-#  %tbody
-#    - @welcomes.each do |welcome|
-#      %tr
-#        %td= welcome.description
-#        %td= link_to 'Show', welcome
-#        %td= link_to 'Edit', edit_welcome_path(welcome)
-#        %td= link_to 'Destroy', welcome, :method => :delete, :data => { :confirm => 'Are you sure?' }
-#
-#%br

%tbody
-#- @welcomes.each do |welcome|
-if @welcomes.count==0
  %td= link_to 'Новое', new_welcome_path, class: "btn btn-primary"
-else
  - @welcomes.each do |welcome|
    %p= markdown(welcome.description)
    - if current_user.try('admin?')
      %td= link_to 'Редактировать', edit_welcome_path(welcome), class: "btn btn-primary"
      %td= link_to 'Удалить', welcome, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "btn btn-primary"

app/views/welcomes/new.html.haml
%h1 Создание новой главной страницы

= render 'form'

= link_to 'Назад', welcomes_path, class: 'btn btn-primary'