config/routes.rb
Rails.application.routes.draw do
  resources :records
  resources :reviews
  resources :contacts
  resources :services
  resources :users
  resources :user_sessions
  resources :welcomes

  # resources :sessions, only: [:new, :create, :destroy]
  root 'welcomes#index'

  # match '/new',    to: 'user_sessions#new',    via: 'get'
  #
  # match '/create',    to: 'user_sessions#create',    via: 'get'
  #
  # match '/destroy',    to: 'user_sessions#destroy',    via: 'get'

  match '/new',    to: 'welcomes#new',    via: 'get'
  match '/create',    to: 'welcomes#create',    via: 'get'
  match '/destroy',    to: 'welcomes#destroy',    via: 'get'

  match '/admin', to: 'users#admin', via: 'get'
  match '/master', to: 'users#master', via: 'get'
  match '/customer', to: 'users#customer', via: 'get'


  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  #
  # get 'user_sessions/new'
  #
  # get 'user_sessions/create'
  #
  # get 'user_sessions/destroy'





end

app/views/layouts/_error_messages_for.html.haml
-if object.errors.any?
  .panel.panel-danger
    .panel-heading
      При сохранении произошли ошибки
    .panel-body
      %ol
        -object.errors.full_messages.each do |msg|
          %li=msg

app/views/layouts/_flash_messages.html.haml
-flash.each do |key, value|
  .alert{class: "alert-#{key}"}
    = value

app/views/layouts/_topbar.html.haml
-#- if current_user.try('admin?') || current_user.try('teacher?')
.navbar
  %ul.nav.navbar-nav.navbar-right
    -if current_user
      %li
        -#-if User.@user.avatar?
        -#  =image_tag @user.avatar.url(:thumb), alt: @user.login
      %li.dropdown
        =link_to ?#,class: 'dropdown-toggle', data: {toggle: 'dropdown'} do

          =current_user.login
          %span.caret
        %ul.dropdown-menu

          %li= link_to 'Просмотр', user_path(current_user.id)
          %li=link_to 'Выход',logout_path
    -else
      %li=link_to "Вход",login_path
      %li=link_to "Регистрация",new_user_path
.navbar.navbar-default
  .container
    .navbar-header
      %ul.nav.navbar-nav
        -#- if current_user
        %li{class: ('active' if controller_name=='welcomes')}=link_to "Главная",welcomes_path, class: 'navbar-brand'
        %li{class: ('active' if controller_name=='records')}=link_to "Запись",records_path, class: 'navbar-brand'
        %li{class: ('active' if controller_name=='services')}=link_to "Услуги",services_path, class: 'navbar-brand'
        %li{class: ('active' if controller_name=='contacts')}=link_to "Контакты",contacts_path, class: 'navbar-brand'
        %li{class: ('active' if controller_name=='reviews')}=link_to "Отзывы",reviews_path, class: 'navbar-brand'

        %li{class: ('active' if controller_name=='users')}=link_to "Наши мастера",master_path, class: 'navbar-brand'
    -#%li{class: ('active' if controller_name=='group_studs')}=link_to "Группы",group_studs_path, class: 'navbar-brand'
        -#%li{class: ('active' if controller_name=='disciplines')}=link_to "Дисциплины",disciplines_path, class: 'navbar-brand'
        -#%li{class: ('active' if controller_name=='blocks')}=link_to "Семестр",blocks_path, class: 'navbar-brand'
      -#%ul.nav.navbar-nav
          -#%li{class: ('active' if controller_name=='tests')}=link_to "Тесты",tests_path, class: 'navbar-brand'
          -#%li{class: ('active' if controller_name=='scenarios')}=link_to "Сценарий",scenarios_path, class: 'navbar-brand'

    %ul.nav.navbar-nav
      - if current_user.try('admin?')
        %li{class: ('active' if controller_name=='users')}=link_to "Пользователи",users_path, class: 'glyphicons glyphicons-glass'
-#-else
-#  %ul.nav.navbar-nav.navbar-right
-#    -if current_user
-#      %li.dropdown
-#        =link_to ?#,class: 'dropdown-toggle', data: {toggle: 'dropdown'} do
-#          =current_user.login
-#          %span.caret
-#        %ul.dropdown-menu
-#          %li=link_to 'Просмотр', user_path(current_user.id)
-#          %li=link_to 'Выход',logout_path
-#    -else
-#      %li=link_to "Вход",login_path
-#      %li=link_to "Регистрация",new_user_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title
      Edu-online
    %meta{charset: 'utf-8'}
    %meta{name: 'viewport', content: "width=device-width, initial-scale=1.0"}
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    #wrap
      .container.main
        = render 'layouts/topbar'
        = render 'layouts/flash_messages'
        = yield



-#- if current_user.try('admin?') || current_user.try('teacher?')
-#  .navbar
-#    - if current_user.try('admin?') || current_user.try('teacher?')
-#      %ul.nav.navbar-nav.navbar-right
-#        -if @current_user
-#          %li.dropdown
-#            =link_to ?#,class: 'dropdown-toggle', data: {toggle: 'dropdown'} do
-#              =@current_user.fio
-#              %span.caret
-#            %ul.dropdown-menu
-#              %li=link_to 'Выход',logout_path
-#        -else
-#          %li=link_to "Вход",login_path
-#          %li=link_to "Регистрация",new_user_path
-#  .navbar.navbar-default
-#    .container
-#      .navbar-header
-#        %ul.nav.navbar-nav
-#          - if current_user.try('admin?')
-#            -#=link_to "Предметы", subjects_path, class: 'navbar-brand'
-#            -#=link_to "Темы", topics_path, class: 'navbar-brand'
-#            -#%li{class: ('active' if controller_name=='group_studs')}=link_to "Группы",group_studs_path, class: 'navbar-brand'
-#            -#%li{class: ('active' if controller_name=='disciplines')}=link_to "Дисциплины",disciplines_path, class: 'navbar-brand'
-#            -#%li{class: ('active' if controller_name=='blocks')}=link_to "Семестр",blocks_path, class: 'navbar-brand'
-#          %ul.nav.navbar-nav
-#            -#%li{class: ('active' if controller_name=='tests')}=link_to "Тесты",tests_path, class: 'navbar-brand'
-#            -#%li{class: ('active' if controller_name=='scenarios')}=link_to "Сценарий",scenarios_path, class: 'navbar-brand'
-#
-#      %ul.nav.navbar-nav
-#        - if current_user.try('admin?')
-#          %li{class: ('active' if controller_name=='users')}=link_to "Пользователи",users_path, class: 'glyphicons glyphicons-glass'
-#-else
-#  %ul.nav.navbar-nav.navbar-right
-#    -if @current_user
-#      %li.dropdown
-#        =link_to ?#,class: 'dropdown-toggle', data: {toggle: 'dropdown'} do
-#          =@current_user.fio
-#          %span.caret
-#        %ul.dropdown-menu
-#          %li=link_to 'Выход',logout_path
-#    -else
-#      %li=link_to "Вход",login_path
-#      %li=link_to "Регистрация",new_user_path
-#